### ISSUE TITLE
能否出个服务器部署教程呢？

### ISSUE THREAD

**Issue by dfaofeng** [MyFaith/douyu-danmu#3]
我直接用nginx指定index.html.开启node server.js。前端页面显示404,能否有个解决方案呢？

**Comment by MyFaith** [comment]
还没开发完......现在只能看弹幕，礼物只能显示一部分

**Comment by dfaofeng** [comment]
> 还没开发完......现在只能看弹幕，礼物只能显示一部分

我现在先把弹幕弄出来,后面的礼物再说,有什么解决办法吗？

**Comment by MyFaith** [comment]
还没部署到服务器上试过，本地开发的时候运行 server.js 然后打开 index.html 就可以了，建议先用其他的，我这个半年多没动过了不确定能生效，抽时间打算重做

**Comment by dfaofeng** [comment]
> 还没部署到服务器上试过，本地开发的时候运行 server.js 然后打开 index.html 就可以了，建议先用其他的，我这个半年多没动过了不确定能生效，抽时间打算重做

有没有其他类型的项目....

**Comment by MyFaith** [comment]
没有...
